services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dsm
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:2.0  # ou eclipse-mosquitto:latest
    container_name: mosquitto-dsm
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_passwords.txt:/mosquitto/config/mosquitto_passwords.txt
volumes:
  mongo_data: